name: ruby-presubmit
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/actions/presubmit-variant/action.yml
      - .github/workflows/ruby-presubmit.yml
      - ruby/**
jobs:
  build:
    name: Verify Ruby variant image (single arch)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: ./.github/actions/presubmit-variant
        with:
          variant: ruby
          archs: amd64
